services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: events
      MYSQL_USER: events
      MYSQL_PASSWORD: events
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      event-network:
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 25

  redis:
    image: "redis:latest"
    container_name: "event-redis"
    ports:
      - "6379:6379"
    networks:
      event-network:
    restart: always

  app:
    container_name: event-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/events
      SPRING_DATASOURCE_USERNAME: events
      SPRING_DATASOURCE_PASSWORD: events
      SPRING_REDIS_HOST: event-redis
      SPRING_REDIS_PORT: 6379
      SPRING_MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET_NAME: event-files
      MINIO_ACCESS_KEY: eventadmin
      MINIO_SECRET_KEY: eventadmin
    ports:
      - "8080:8080"
    networks:
      event-network:
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    environment:
      #La password tiene que tener 8 o mas caracteres
      MINIO_ROOT_USER: eventadmin
      MINIO_ROOT_PASSWORD: eventadmin
    ports:
      - "9000:9000"
#     - "9001:9001"
    networks:
      event-network:
    volumes:
      - minio_data:/data
    command: server /data

networks:
  event-network:

volumes:
  mysql_data:
  minio_data:
